x-controller:
  &controller-template
  tmpfs: /tmp
  environment:
    - CCACHE_DIR=/mnt/ccache
    - CCACHE_CONFIGPATH=/mnt/ccache/ccache.conf
  secrets:
    - github_apikey
  volumes:
    - ccache:/mnt/ccache
    - ./tmp_config:/mnt/config
    - ./tmp_builds:/mnt/builds
  network_mode: "host"
  dns: 8.8.8.8

services:
  controller-050:
    << : *controller-template
    build:
      context: .
      dockerfile: Dockerfile
      target: controller
      args:
        - TAG=v0.5.0
    image: kiisrv-controller-050:latest

  controller-054:
    << : *controller-template
    build:
      context: .
      dockerfile: Dockerfile
      target: controller
      args:
        - TAG=v0.5.4
    image: kiisrv-controller-054:latest

  controller-055:
    << : *controller-template
    build:
      context: .
      dockerfile: Dockerfile
      target: controller
      args:
        - TAG=v0.5.5
    image: kiisrv-controller-055:latest

  controller-056:
    << : *controller-template
    build:
      context: .
      dockerfile: Dockerfile
      target: controller
      args:
        - TAG=v0.5.6
    image: kiisrv-controller-056:latest

  controller-057:
    << : *controller-template
    build:
      context: .
      dockerfile: Dockerfile
      target: controller
      args:
        - TAG=v0.5.7
    image: kiisrv-controller-057:latest

secrets:
  github_apikey:
    file: ./apikey

volumes:
  ccache:
